name: Build Affinity Wine
on:
  push:
    paths:
      - ".github/workflows/builder.yml"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Essentials
      - run: apt install -y git gcc-mingw-w64 gcc-multilib libasound2-dev libcups2-dev libdbus-1-dev libfontconfig-dev libfreetype-dev libgl-dev libgnutls28-dev libgphoto2-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libosmesa6-dev libpcap-dev libpulse-dev libsane-dev libsdl2-dev libudev-dev libunwind-dev libusb-1.0-0-dev libvulkan-dev libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxfixes-dev libxi-dev libxrandr-dev libxrender-dev ocl-icd-opencl-dev samba-dev
      - name: clone rum
      - run: mkdir -p $HOME/Documents && git clone https://gitlab.com/xkero/rum $HOME/Documents/rum && cp $HOME/Documents/rum/rum /usr/local/bin/rum
      - name: Compiling Wine
      - run: 'git clone https://gitlab.winehq.org/ElementalWarrior/wine.git ElementalWarrior-wine && cd ElementalWarrior-wine && git switch affinity-photo2-wine8.14 && mkdir winewow64-build/ wine-install/ && cd winewow64-build/ && ../configure --prefix="$HOME/Documents/ElementalWarrior-wine/wine-install" --enable-archs=i386,x86_64 && make --jobs 4 && make install'
      - name: Setting up the build
      - run: mkdir /opt/wines && cp --recursive "$HOME/Documents/ElementalWarrior-wine/wine-install" "/opt/wines/ElementalWarrior-8.14" && tar -cvf /opt/wines.tar /opt/wines
      - name: Upload to Github Artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: /opt/wines.tar
          tag: 'yes'
          overwrite: true
          file_glob: true
          body: "New Release."
